name: AstroViewingConditions
options:
  bundleIdPrefix: com.astroviewing
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "16.0"

settings:
  base:
    SWIFT_VERSION: "6.0"
    TARGETED_DEVICE_FAMILY: "1,2"
    SUPPORTS_MACCATALYST: NO

packages:
  SunCalc:
    url: https://github.com/nikolajjensen/SunCalc.git
    from: "1.0.0"

targets:
  AstroViewingConditions:
    type: application
    platform: iOS
    sources:
      - Sources
    resources:
      - Sources/AstroViewingConditions/Resources/Assets.xcassets
    settings:
      base:
        INFOPLIST_FILE: Sources/App/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.astroviewing.conditions
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: YES
    dependencies:
      - package: SunCalc

schemes:
  AstroViewingConditions:
    build:
      targets:
        AstroViewingConditions: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
